### ISSUE TITLE
topojson-svg could have an option to keep properties as data attributes

### ISSUE THREAD

**Issue by kapouer** [topojson/topojson#260] opened 2015-11-03 14:55 UTC
Something like
https://github.com/mbostock/topojson/commit/070ff4bd87ff1ac496385c77cf2170977dac91f9
but i don't really get how optimist handles lists.

**Comment by mbostock** [comment] 2016-10-31 20:45
Duplicate of #261; moved to d3/d3-geo-projection#74.

**Closed by mbostock** 2016-10-31 20:45 UTC
