### ISSUE TITLE
Merging two files into one object

### ISSUE THREAD

**Issue by ninjatronic** [topojson/topojson#240] opened 2015-05-11 18:54 UTC
Is there any way to merge two files into one object?

I have a map of regions in England and Wales and a map of regions in Scotland from [here](https://github.com/martinjc/UK-GeoJSON). I want to create a map of all the regions in England, Wales and Scotland with the data all in one object.

At the moment this is my script...

``` bash
curl https://raw.githubusercontent.com/martinjc/UK-GeoJSON/master/json/eurostat/ew/nuts2.json > ./ew.json
curl https://raw.githubusercontent.com/martinjc/UK-GeoJSON/master/json/eurostat/sco/nuts2.json > ./sco.json

topojson -o ./uk.json --id-property NUTS212NM -- ./ew.json ./sco.json

```

This creates a topoJSON file with two objects (ew and sco). I'd like to just have one object (gb). Is this possible?

Thanks

**Comment by aubergene** [comment] 2016-06-13 11:54
Just as a note as to how I worked around this. I did a very naive approach where I was merging two objects of `type: 'GeometryCollection'` so I just concatenated the `geometries` arrays together and removed `bbox` which is optional according to the spec.

**Comment by bradoyler** [comment] 2016-08-29 20:12
Any ideas on why this doesn't work? based on the usage: `Usage: topojson [options] -- [file …]`
it looks like it should...

**Comment by mbostock** [comment] 2016-10-31 21:52
Duplicate of #239; this should be covered by topomerge in 2.0 (and previously [topojson-merge](https://github.com/topojson/topojson/blob/v1.6.27/bin/topojson-merge)); see topojson/topojson-client#3.

**Closed by mbostock** 2016-10-31 21:52 UTC

**Comment by mbostock** [comment] 2016-10-31 21:54
Actually, I guess this is slightly different in that you want to combine the input geometries without merging (dissolving) them. But in 2.0 you should be able to do that pretty easily just using `cat` and newline-delimited JSON input streams.

**Comment by viren1** [comment] 2017-12-05 23:51
In topojson@1
 if multiple files were to be added into one single object, the command used to be
"**topojson  -o main.json**  _subunits.topojson   places.topojson   states.topojson_"

is there an equivalent command for this in topojson@3
after doing the following steps

shp2json -n ne_10m_admin_0_map_subunits.shp | ndjson-filter "['USA'].includes(d.properties.ADM0_A3, d.properties.iso_a2)" > subunits.ndjson
shp2json -n ne_10m_populated_places.shp | ndjson-filter "['US'].includes(d.properties.ISO_A2)" > places.ndjson
shp2json -n ne_10m_admin_1_states_provinces_lakes_shp.shp | ndjson-filter "['US'].includes(d.properties.iso_a2)" > states.ndjson

ndjson-map "(d.id = d.properties.iso_a2, d)" <  "C:\Users\USER\subunits.ndjson" >  xsubunits.json"
ndjson-map "(d.id = d.properties.iso_a2, d)" <  "C:\Users\USER\places.ndjson" >  xplaces.json"
ndjson-map "(d.id = d.properties.iso_a2, d)" <  "C:\Users\USER\states.ndjson" >  xstates.json"

geostitch -n < xsubunits.json" > subunits.json"
geostitch -n < xplaces.json" > places.json"
geostitch -n < xstates.json" > states.json"

geo2topo -q 1e5 -n subunits=subunits.json" > subunits.topojson"
geo2topo -q 1e5 -n places=places.json" > places.topojson"
geo2topo -q 1e5 -n states=states.json" > states.topojson"

Thanks

**Comment by aubergene** [comment] 2017-12-06 00:29
As they are newline delimited already, you should be able to just merge them together with `cat` before you transform them to topojson.
