### ISSUE TITLE
Typescript typings

### ISSUE THREAD

**Issue by ValeryVS** [topojson/topojson#300] opened 2016-12-12 17:09 UTC
Is there are any typescript typings?
It will be good to have such.

Fro utility and for topojson objects, both.

**Comment by mbostock** [comment] 2016-12-12 17:21
Duplicate of #290. A Google search suggests [ts-topojson](https://www.npmjs.com/package/ts-topojson) might be worth looking into. I do not maintain bindings for other languages.

**Closed by mbostock** 2016-12-12 17:21 UTC
