### ISSUE TITLE
Issue with converting topology MultiPolygon to geojson

### ISSUE THREAD

**Issue by GermisMc** [topojson/topojson#298] opened 2016-11-28 14:37 UTC
I know that topojson when converting from `geojson` to `topology` is represent `Multypolygon` as `Polygon` with special structure of the array. But at reverse conversion (`topology` in `geojson`) he does it with an error and it does not replace the type to `Multipolygon` and does not replace the structure of the array.
For example:

Geojson
```json 
{
	"type" : "Feature",
	"geometry" : {
		"type" : "MultiPolygon",
		"coordinates" : [[[[3.9861, 50.9162], [3.9862, 50.916], [3.9864, 50.9156], [3.9866, 50.9152], [3.9868, 50.9148], ..., [3.9871, 50.9143]], [[3.9874, 50.9139], ..., [3.9887, 50.8948], [3.9885, 50.8947]]]]
}
```

Convert to the topology
```json
{
	"type" : "Polygon",
	"arcs" : [[-5165, -4394, -4390, -4749, -4016, -4750, -2247, 5326], [-2518]]
}
```

Convert back from a topology to geojson

![finalgeo](https://cloud.githubusercontent.com/assets/11063519/20671859/1f711eaa-b590-11e6-82ae-302afb9284c8.PNG)

To convert from `geojson` to the `topology`, we use the command line `topojson` for the reverse conversion, we use the `topojson.feature()` method in javascript.

**Comment by mbostock** [comment] 2016-11-28 15:33
Let me see if I understand your issue correctly.

The current behavior of [geo2topo](https://github.com/topojson/topojson/blob/master/README.md#geo2topo) ([topojson.topology](https://github.com/topojson/topojson/blob/master/README.md#topology)) is that it “optimizes” input geometries, choosing the smallest GeoJSON type that accurately represents the input geometry. (See [geometry.js](https://github.com/topojson/topojson/blob/master/src/geometry.js).) Specifically this means:

* A MultiPolygon with *coordinates*.length of zero becomes null.
* A MultiPolygon with *coordinates*.length of ones becomes a Polygon.
* A Polygon with *coordinates*.length of zero becomes null.
* A MultiLineString with *coordinates*.length of zero becomes null.
* A MultiLineString with *coordinates*.length of one becomes a LineString.
* A LineString with *coordinates*.length of zero becomes null.
* A MultiPoint with *coordinates*.length of zero becomes null.
* A MultiPoint with *coordinates*.length of one becomes a Point.

The behavior you expect is that geo2topo and topojson.topology preserve the input type, correct?

Perhaps we could break this functionality out into a separate utility, or remove it entirely. I think my intent was to make the output TopoJSON as small as possible (and as fast to render as possible), but I don’t expect this optimization to be significant in any case, and so perhaps it’d be better to preserve the input type exactly.

**Comment by GermisMc** [comment] 2016-11-29 11:09
It seems that geo2topo works correctly, but with features. And these features need to be considered in topo2geo conversion.
Namely, we need to change the type from `Polygon` to `MultiPolygon` depending on the structure of the array geometry. And also need to change the structure geometry to make it look like this for MultiPolygon:
![multipolygon](https://cloud.githubusercontent.com/assets/11063519/20707696/78816b1e-b63d-11e6-8bd7-68abb8b01e84.PNG)

**Comment by mbostock** [comment] 2016-11-29 17:10
Not sure I understand you. TopoJSON doesn’t have a “Feature” type. It uses only geometry objects, but those geometry objects can have properties hashes (similar to GeoJSON features). So the conversion from GeoJSON to TopoJSON always converts GeoJSON features to TopoJSON geometries, in addition to the geometry type reductions described in my previous comment.

The geometry type reduction is lossy (that is, it loses information), so there’s no way to undo it in topo2geo. For example, if your input GeoJSON is a MultiPolygon geometry representing exactly one polygon, geo2topo will convert this to a Polygon. This is indistinguishable from the input GeoJSON being a Polygon geometry, so there’s no way for geo2topo to know that it should promote the Polygon geometry back to a MultiPolygon. (Unless you wanted to promote *all* Polygon geometries to MultiPolygon… but that doesn’t make a lot of sense.)

The reduced types are valid and equivalent to the original geometries, so for the vast majority of cases the current behavior of geo2topo is acceptable (and even preferred because it is slightly smaller). But I do think it would be reasonable to make this behavior optional, and perhaps even disable it by default since the performance gain is so small, and there *are* conceivably cases where the consumer of the resulting TopoJSON wants to preserve the input geometry types exactly rather than losing information.

**Comment by GermisMc** [comment] 2016-11-30 12:47
Sorry for my English, by the word "feature", I mean non-standard behavior. Overall I think you caught the problem. Simplification types sometimes works incorrectly in this case. 

If you look at the screenshot of the browser in the first message you can see that topo2geo made a mistake here. The coordinates array contains 2 elements (region and a hole in it) that already says that it is MultiPolygon, but he Polygon.

The idea of disabling reduced types could help I think.

**Comment by mbostock** [comment] 2016-11-30 15:14
It sounds like you are describing a different (!) bug which is not simply the conversion from MultiPolygon to Polygon when the coordinates.length is one, but some other big where the conversion is incorrectly implemented resulting in an invalid MultiPolygon. However, you haven’t provided enough information for me to investigate. I need:

* The input files to reproduce the invalid output.
* The exact sequence of commands run to produce the invalid output.

The behavior we discussed is only the reduction of types such as from MultiPolygob to Polygon. No where in the code goes the other way (from Polygon to MultiPolygon), which suggests that the problem is not in geo2topo or topo2geo but in your input before it reaches these libraries.

Hence the need to know how you got to this point if you want me to investigate.

**Comment by mbostock** [comment] 2016-11-30 15:22
Actually rereading this entire thread, I think you may simply be misunderstanding the GeoJSON Polygon type. If you read the GeoJSON specification you will see that the Polygon geometry type represents multiple rings: one exterior ring followed by zero or more interior holes. This, multiple rings does not require a MultiPolygon; the latter is used only when there are multiple *exterior* rings.

I am going to close this bug assuming I understood the confusion, but if I was wrong, please reply and I will continue to investigate. I will also file a separate issue about disabling the automatic type reduction, but it sounds like that was not the problem here.

**Closed by mbostock** 2016-11-30 15:22 UTC
